project:
  type: website
  output-dir: docs

website:
  title: "Chris Carr"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://linkedin.com/in/chrisdavidcarr
      - icon: github
        href: https://github.com/chrisdavidcarr
      - icon: twitter-x
        href: https://x.com/chrisdavidcarr
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



